[project]
name = "vatcomply"
version = "0.1.0"
requires-python = ">=3.11, <=3.12"

[tool.isort]
profile = "black"

[tool.black]
line-length = 100
target-version = ['py313']

[tool.pyright]
venvPath = "."
venv = ".venv"
