# Generated by Django 6.0.1 on 2026-02-20 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authtoken',
            name='users_autht_key_f22218_idx',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='key',
            field=models.CharField(max_length=40, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
