# Generated by Django 4.2.8 on 2023-12-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "iso2",
                    models.CharField(
                        max_length=2, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("iso3", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=200)),
                ("numeric_code", models.IntegerField()),
                ("phone_code", models.CharField(max_length=3)),
                ("capital", models.CharField(max_length=200)),
                ("currency", models.CharField(max_length=200)),
                ("tld", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=200)),
                ("subregion", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("emoji", models.CharField(max_length=1)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("rates", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
