# Generated by Django 6.0.1 on 2026-02-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vatcomply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
