# Generated by Django 6.0.2 on 2026-02-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vatcomply', '0002_alter_country_emoji_alter_country_phone_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('country_name', models.CharField(max_length=200)),
                ('standard_rate', models.FloatField()),
                ('reduced_rates', models.JSONField(default=list)),
                ('super_reduced_rate', models.FloatField(null=True)),
                ('parking_rate', models.FloatField(null=True)),
                ('currency', models.CharField(default='', max_length=10)),
                ('member_state', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country_code'],
            },
        ),
    ]
