# Generated by Django 6.0.3 on 2026-03-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vatcomply', '0003_vatrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatrate',
            name='rate_comments',
            field=models.JSONField(default=dict),
        ),
    ]
