# Generated by Django 6.0.3 on 2026-03-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vatcomply', '0004_vatrate_rate_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatrate',
            name='rate_categories',
            field=models.JSONField(default=dict),
        ),
    ]
