"""create countries table

Revision ID: 17ee4cab92e6
Revises: c8d6ab7251df
Create Date: 2021-10-11 22:44:08.477311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17ee4cab92e6"
down_revision = "c8d6ab7251df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("iso2", sa.String(), nullable=False),
        sa.Column("iso3", sa.String(), nullable=False),
        sa.Column("numeric_code", sa.String(), nullable=True),
        sa.Column("phone_code", sa.String(), nullable=True),
        sa.Column("capital", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("tld", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("subregion", sa.String(), nullable=False),
        sa.Column("latitude", sa.String(), nullable=False),
        sa.Column("longitude", sa.String(), nullable=False),
        sa.Column("emoji", sa.String(), nullable=False),
        sa.UniqueConstraint("iso2"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("countries")
    # ### end Alembic commands ###
