from django.db import models
from babel.numbers import get_currency_name


class CurrencySymbol(models.TextChoices):
    EUR = "EUR", get_currency_name("EUR", locale="en")
    USD = "USD", get_currency_name("USD", locale="en")
    JPY = "JPY", get_currency_name("JPY", locale="en")
    BGN = "BGN", get_currency_name("BGN", locale="en")
    CZK = "CZK", get_currency_name("CZK", locale="en")
    DKK = "DKK", get_currency_name("DKK", locale="en")
    GBP = "GBP", get_currency_name("GBP", locale="en")
    HUF = "HUF", get_currency_name("HUF", locale="en")
    PLN = "PLN", get_currency_name("PLN", locale="en")
    RON = "RON", get_currency_name("RON", locale="en")
    SEK = "SEK", get_currency_name("SEK", locale="en")
    CHF = "CHF", get_currency_name("CHF", locale="en")
    ISK = "ISK", get_currency_name("ISK", locale="en")
    NOK = "NOK", get_currency_name("NOK", locale="en")
    HRK = "HRK", get_currency_name("HRK", locale="en")
    RUB = "RUB", get_currency_name("RUB", locale="en")
    TRY = "TRY", get_currency_name("TRY", locale="en")
    AUD = "AUD", get_currency_name("AUD", locale="en")
    BRL = "BRL", get_currency_name("BRL", locale="en")
    CAD = "CAD", get_currency_name("CAD", locale="en")
    CNY = "CNY", get_currency_name("CNY", locale="en")
    HKD = "HKD", get_currency_name("HKD", locale="en")
    IDR = "IDR", get_currency_name("IDR", locale="en")
    ILS = "ILS", get_currency_name("ILS", locale="en")
    INR = "INR", get_currency_name("INR", locale="en")
    KRW = "KRW", get_currency_name("KRW", locale="en")
    MXN = "MXN", get_currency_name("MXN", locale="en")
    MYR = "MYR", get_currency_name("MYR", locale="en")
    NZD = "NZD", get_currency_name("NZD", locale="en")
    PHP = "PHP", get_currency_name("PHP", locale="en")
    SGD = "SGD", get_currency_name("SGD", locale="en")
    THB = "THB", get_currency_name("THB", locale="en")
    ZAR = "ZAR", get_currency_name("ZAR", locale="en")
